// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjWn5iVrxDR5bKwYLw7NCBCYP8Jp6nLM',
    appId: '1:196822526321:android:0ed077821f788a3d062ed0',
    messagingSenderId: '196822526321',
    projectId: 'kronk-dev-2',
    storageBucket: 'kronk-dev-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBapiYg7sSBp4zfoPqq0ReHgizHFnldLjQ',
    appId: '1:196822526321:ios:2bd087082945edd0062ed0',
    messagingSenderId: '196822526321',
    projectId: 'kronk-dev-2',
    storageBucket: 'kronk-dev-2.firebasestorage.app',
    androidClientId: '196822526321-3ov98tgd3hdukut25ll7t7vjihep6vde.apps.googleusercontent.com',
    iosClientId: '196822526321-1osqmsrgp96n5p323h2skhe413n8nngq.apps.googleusercontent.com',
    iosBundleId: 'com.kronk.kronk',
  );
}
